general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: fake-openai-endpoint
    - model_name: anthropic-vertex
      litellm_params:
        model: vertex_ai/claude-3-sonnet@20240229
        vertex_ai_project: "my-test-project"
        vertex_ai_location: "us-east-1"
    - model_name: anthropic-vertex
      litellm_params:
        model: vertex_ai/claude-3-sonnet@20240229
        vertex_ai_project: "my-test-project"
        vertex_ai_location: "us-west-1"
    model_name: anthropic-vertex
      litellm_params:
        model: vertex_ai/claude-3-5-sonnet-v2@20241022
        vertex_ai_project: "my-test-project"
        vertex_ai_location: "us-west-1"

litellm_settings:
  drop_params: True
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  service_callback: ["prometheus_system"]

